const router=require('express').Router();const bcrypt=require('bcryptjs');const crypto=require('node:crypto');const db=require('../db');
const {requireCustomer,setSession}=require('../middleware/customer-auth');const {phone,address,fail}=require('../services/commerce-quote');
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);const email=v=>String(v||'').trim().toLowerCase();const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
router.use((req,res,next)=>{res.set('Cache-Control','no-store');next()});
router.post('/register',require('../middleware/rate-limit')(8,600000),wrap(async(req,res)=>{const b=req.body;if((await require('../services/commerce-settings').getSettings('accounts')).registration_enabled===false)fail('New account registration is currently closed.',403);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email(b.email))||email(b.email).length>254||typeof b.password!=='string'||b.password.length<10||Buffer.byteLength(b.password)>72||!String(b.name||'').trim())fail('Enter a name, email and password of 10–72 characters.');const password=await bcrypt.hash(b.password,12);const {rows}=await db.query('INSERT INTO customers(email,name,phone,password_hash) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO NOTHING RETURNING id,name,email,phone,session_version',[email(b.email),String(b.name).trim().slice(0,150),phone(b.phone),password]);if(!rows[0])fail('Unable to create this account. Try signing in or resetting your password.',409);setSession(res,rows[0]);res.status(201).json({customer:rows[0]});}));
router.post('/login',require('../middleware/rate-limit')(15,600000),wrap(async(req,res)=>{
const staff=(await db.query("SELECT * FROM admin_users WHERE email=$1",[email(req.body.email)])).rows[0];
if(staff&&staff.status==='ACTIVE'&&['ADMIN','SUPER_ADMIN','STAFF'].includes(staff.role)&&await bcrypt.compare(String(req.body.password||''),staff.password_hash)){const token=require('jsonwebtoken').sign({id:staff.id,email:staff.email,role:staff.role,session_version:staff.session_version},process.env.ADMIN_JWT_SECRET,{expiresIn:'12h'});return res.json({token,admin:{id:staff.id,email:staff.email,role:staff.role},redirect:'/admin/manage.html'});}
const {rows}=await db.query("SELECT * FROM customers WHERE email=$1 AND status='ACTIVE'",[email(req.body.email)]);const c=rows[0];const valid=await bcrypt.compare(String(req.body.password||''),c?.password_hash||'$2b$12$wEZnsMUfVU/L77NGuew0ZOdIl6RbAGofEhNCIO/NusI3nmaIwSwOu');if(!c||!valid)fail('Incorrect email or password.',401);setSession(res,c);res.json({customer:{id:c.id,name:c.name,email:c.email,phone:c.phone}});}));
router.post('/logout',(req,res)=>{res.clearCookie('mikyaj_customer',{path:'/'});res.json({success:true});});
router.post('/forgot-password',require('../middleware/rate-limit')(5,600000),wrap(async(req,res)=>{if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)fail('Password recovery email is not configured. Please contact the store.',503);const c=(await db.query("SELECT id FROM customers WHERE email=$1 AND status='ACTIVE'",[email(req.body.email)])).rows[0];if(c){const token=crypto.randomBytes(32).toString('hex');await db.query("INSERT INTO password_resets(token_hash,customer_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')",[hash(token),c.id]);const url=(process.env.FRONTEND_URL||'https://mikyajkw.com')+'/account.html?reset='+token;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.EMAIL_FROM,to:email(req.body.email),subject:'Mikyaj — Reset your password / إعادة تعيين كلمة المرور',text:'Reset your password within 30 minutes / أعد تعيين كلمة المرور خلال 30 دقيقة: '+url}),signal:AbortSignal.timeout(15000)});if(!response.ok)fail('Unable to send recovery email. Please try later.',503);}res.json({success:true,message:'If an account exists, a reset email will arrive shortly.'});}));
router.post('/reset-password',require('../middleware/rate-limit')(10,600000),wrap(async(req,res)=>{const password=req.body.password;if(typeof password!=='string'||password.length<10||Buffer.byteLength(password)>72)fail('Use a password of 10–72 characters.');const client=await db.pool.connect();try{await client.query('BEGIN');const r=(await client.query('SELECT * FROM password_resets WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW() FOR UPDATE',[hash(String(req.body.token||''))])).rows[0];if(!r)fail('This reset link is invalid or expired.');await client.query('UPDATE customers SET password_hash=$1,session_version=session_version+1 WHERE id=$2',[await bcrypt.hash(password,12),r.customer_id]);await client.query('UPDATE password_resets SET used_at=NOW() WHERE token_hash=$1',[r.token_hash]);await client.query('COMMIT');res.json({success:true});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}));
router.use(requireCustomer);
router.put('/addresses/:id',wrap(async(req,res)=>{const a=address(req.body),client=await db.pool.connect();try{await client.query('BEGIN');await client.query('SELECT id FROM customers WHERE id=$1 FOR UPDATE',[req.customer.id]);if(req.body.is_default===true)await client.query('UPDATE customer_addresses SET is_default=false WHERE customer_id=$1',[req.customer.id]);const values=[String(req.body.label||'Home').slice(0,50),...Object.values(a),req.body.is_default===true,Number(req.params.id)||0,req.customer.id];const result=await client.query('UPDATE customer_addresses SET label=$1,'+Object.keys(a).map((k,i)=>k+'=$'+(i+2)).join(',')+',is_default=$10 WHERE id=$11 AND customer_id=$12 RETURNING id',values);if(!result.rows.length)fail('Address not found',404);await client.query('COMMIT');res.json({success:true});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}));
router.get('/me',(req,res)=>res.json({customer:req.customer}));
router.put('/me',wrap(async(req,res)=>{const name=String(req.body.name||'').trim().slice(0,150);if(!name)fail('Name is required');await db.query('UPDATE customers SET name=$1,phone=$2,updated_at=NOW() WHERE id=$3',[name,phone(req.body.phone),req.customer.id]);res.json({success:true});}));
router.get('/addresses',wrap(async(req,res)=>res.json((await db.query('SELECT * FROM customer_addresses WHERE customer_id=$1 ORDER BY is_default DESC,id DESC',[req.customer.id])).rows)));
router.post('/addresses',wrap(async(req,res)=>{const a=address(req.body);const keys=Object.keys(a);const values=[req.customer.id,String(req.body.label||'Home').slice(0,50),...Object.values(a)];const {rows}=await db.query(`INSERT INTO customer_addresses(customer_id,label,${keys.join(',')}) VALUES(${values.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING id`,values);res.status(201).json(rows[0]);}));
router.delete('/addresses/:id',wrap(async(req,res)=>{const r=await db.query('DELETE FROM customer_addresses WHERE id=$1 AND customer_id=$2 RETURNING id',[Number(req.params.id)||0,req.customer.id]);if(!r.rows.length)fail('Address not found',404);res.json({success:true});}));
router.get('/orders',wrap(async(req,res)=>res.json((await db.query('SELECT order_number,total_amount,status,payment_method,created_at FROM orders WHERE customer_id=$1 ORDER BY id DESC LIMIT 100',[req.customer.id])).rows)));
module.exports=router;
