const router=require('express').Router(),db=require('../db');
const {audit}=require('../services/commerce-settings'),{fail}=require('../services/commerce-quote');
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
router.get('/discounts',wrap(async(req,res)=>res.json((await db.query("SELECT d.*,(SELECT COUNT(*)::int FROM discount_redemptions r WHERE r.discount_id=d.id AND NOT released) AS uses,CASE WHEN NOT active THEN 'Disabled' WHEN starts_at>NOW() THEN 'Scheduled' WHEN ends_at<=NOW() THEN 'Expired' ELSE 'Active' END state FROM discounts d ORDER BY id DESC LIMIT 500")).rows)));
function parse(b){const f={title:String(b.title||'').trim().slice(0,200),title_ar:String(b.title_ar||'').trim().slice(0,200),type:b.type,method:b.method,code:b.method==='CODE'?String(b.code||'').trim().toUpperCase():null,value_type:b.value_type||'PERCENT',value:Number(b.value||0),target:b.target||'ALL',get_target:b.get_target||'ALL',minimum_amount:Number(b.minimum_amount||0),buy_quantity:Number(b.buy_quantity||1),get_quantity:Number(b.get_quantity||1),usage_limit:b.usage_limit?Number(b.usage_limit):null,once_per_customer:b.once_per_customer===true,combines:b.combines===true,active:b.active!==false,starts_at:b.starts_at?new Date(b.starts_at):new Date(),ends_at:b.ends_at?new Date(b.ends_at):null};
 if(!f.title||!['PRODUCT','ORDER','BXGY','SHIPPING'].includes(f.type)||!['AUTOMATIC','CODE'].includes(f.method)||f.code&&!/^[A-Z0-9_-]{3,40}$/.test(f.code)||f.method==='CODE'&&!f.code)fail('Supply a title, discount type and valid code if needed.');
 if(!['PERCENT','FIXED'].includes(f.value_type)||!Number.isFinite(f.value)||f.value<0||f.value>999999||f.value_type==='PERCENT'&&f.value>100||!Number.isFinite(f.minimum_amount)||f.minimum_amount<0||f.minimum_amount>999999)fail('Invalid discount value or minimum.');
 if(f.type!=='SHIPPING'&&f.value<=0)fail('Discount value must be positive.');
 for(const key of ['buy_quantity','get_quantity'])if(!Number.isInteger(f[key])||f[key]<1||f[key]>99)fail('Buy/get quantities must be 1–99.');if(f.usage_limit!==null&&(!Number.isInteger(f.usage_limit)||f.usage_limit<1))fail('Invalid usage limit');
 if(!Number.isFinite(+f.starts_at)||f.ends_at&&(!Number.isFinite(+f.ends_at)||f.ends_at<=f.starts_at))fail('Invalid discount dates');
 for(const[key,target]of [['target_ids','target'],['get_ids','get_target']]){if(!['ALL','PRODUCTS','CATEGORIES','BRANDS'].includes(f[target]))fail('Invalid target');f[key]=Array.isArray(b[key])?[...new Set(b[key].map(Number))]:[];if(f[key].length>500||f[key].some(n=>!Number.isSafeInteger(n)||n<1)||f[target]!=='ALL'&&!f[key].length)fail('Select eligible products, categories or brands.');}
 return f;
}
async function save(req,res){const fields=parse(req.body);let r;if(req.params.id){const values=Object.values(fields);values.push(Number(req.params.id)||0);r=await db.query(`UPDATE discounts SET ${Object.keys(fields).map((k,i)=>k+'=$'+(i+1)).join(',')},updated_at=NOW() WHERE id=$${values.length} RETURNING id`,values)}else r=await db.query(`INSERT INTO discounts(${Object.keys(fields).join(',')}) VALUES(${Object.keys(fields).map((_,i)=>'$'+(i+1)).join(',')}) RETURNING id`,Object.values(fields));if(!r.rows.length)fail('Discount not found',404);await audit(req.admin.id,'discount.save',r.rows[0].id);res.json(r.rows[0])}
router.post('/discounts',wrap(save));router.put('/discounts/:id',wrap(save));
router.patch('/discounts/:id',wrap(async(req,res)=>{if(typeof req.body.active!=='boolean')fail('Invalid discount status');const r=await db.query('UPDATE discounts SET active=$1,updated_at=NOW() WHERE id=$2 RETURNING id',[req.body.active,Number(req.params.id)||0]);if(!r.rows.length)fail('Discount not found',404);await audit(req.admin.id,'discount.status',req.params.id);res.json({success:true})}));
router.delete('/discounts/:id',wrap(async(req,res)=>{const r=await db.query('DELETE FROM discounts WHERE id=$1 AND NOT EXISTS(SELECT 1 FROM discount_redemptions WHERE discount_id=$1) RETURNING id',[Number(req.params.id)||0]);if(!r.rows.length)fail('Used discounts must be disabled to preserve order history.',409);await audit(req.admin.id,'discount.delete',req.params.id);res.json({success:true})}));
module.exports=router;
