const router=require('express').Router();
const crypto=require('node:crypto');
const db=require('../db');
const {requireAdminAuth}=require('../middleware/admin-auth');
const catalog=require('../services/catalog');
const settings=require('../services/commerce-settings');
const {fail}=require('../services/commerce-quote');
router.use(requireAdminAuth,(req,res,next)=>{res.set('Cache-Control','no-store');next()});
router.use(require('./product-fields'));
router.use(require('./content-admin'));
router.use(require('./banners-admin'));
router.use(require('./returns-admin'));
router.use(require('./discounts-admin'));
router.use(require('./config-admin'));
router.use(require('./operations-admin'));
router.use(require('./catalog-admin'));
router.use(require('./variants-admin'));
router.use(require('./order-documents-admin'));
router.use(require('./page-visits-admin'));
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
const id=v=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<1)fail('Invalid ID');return n;};
const text=(v,max=10000)=>String(v??'').trim().slice(0,max);
const slug=v=>{const s=text(v,180);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s))fail('Use lowercase letters, numbers and hyphens for the URL.');return s;};
const money=v=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>999999)fail('Invalid price');return n.toFixed(3);};
const priority=v=>{const n=Number(v||0);if(!Number.isInteger(n)||Math.abs(n)>100000)fail('Invalid priority');return n;};
const imageUrl=v=>{if(!v)return null;let u;try{u=new URL(v)}catch{fail('Invalid image URL')};if(u.protocol!=='https:'||u.hostname!=='res.cloudinary.com')fail('Use a Cloudinary HTTPS image URL.');return u.href;};
router.post('/images',wrap(async(req,res)=>{if(typeof req.body.data!=='string'||!/^data:image\/(jpeg|png|webp);base64,/.test(req.body.data)||req.body.data.length>5600000)fail('Upload a JPEG, PNG or WebP smaller than 4 MB.');const cloudinary=require('cloudinary').v2;cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET,secure:true});if(!process.env.CLOUDINARY_API_SECRET)fail('Image uploads are not configured on the server.',503);const r=await cloudinary.uploader.upload(req.body.data,{folder:'mikyaj/products',resource_type:'image',transformation:[{width:1600,height:1600,crop:'limit',quality:'auto',fetch_format:'webp'}]});res.json({url:r.secure_url});}));
router.get('/session',wrap(async(req,res)=>res.json({admin:req.admin})));
router.get('/products',wrap(async(req,res)=>res.json(await catalog.listProducts(req.query,true))));
router.get('/products/:id',wrap(async(req,res)=>{const {rows}=await db.query('SELECT slug FROM products WHERE id=$1 AND deleted_at IS NULL',[id(req.params.id)]);if(!rows[0])fail('Product not found',404);res.json({product:await catalog.product(rows[0].slug,true)});}));
router.patch('/products/:id/state',wrap(async(req,res)=>{
 const productId=id(req.params.id),action=req.body.action;
 const changes={live:"status='ACTIVE',stock_status='IN_STOCK'",unlist:"status='INACTIVE'",out_of_stock:"status='ACTIVE',stock_status='OUT_OF_STOCK'",delete:"status='INACTIVE',deleted_at=NOW()"};
 if(!changes[action])fail('Invalid action');
 const result=await db.query(`UPDATE products SET ${changes[action]},updated_at=NOW() WHERE id=$1 AND deleted_at IS NULL RETURNING id`,[productId]);if(!result.rows.length)fail('Product not found',404);
 await settings.audit(req.admin.id,'product.'+action,productId);res.json({success:true});
}));
async function saveProduct(req,res){
 const b=req.body;if(!text(b.name_ar,500))fail('Arabic product name is required.');
 const productSlug=slug(b.slug),categoryId=id(b.category_id),brandId=b.brand_id?id(b.brand_id):null;
 const price=money(b.selling_price);if(Number(price)<=0)fail('Selling price must be positive.');
 const regular=b.regular_price?money(b.regular_price):null;if(regular!==null&&Number(regular)<Number(price))fail('Regular price must not be lower than selling price.');
 if(!['ACTIVE','INACTIVE'].includes(b.status)||!['IN_STOCK','OUT_OF_STOCK'].includes(b.stock_status))fail('Invalid product state.');
 const steps=['','cleanser','toner','serum','moisturizer','sunscreen','primer','foundation','concealer','setting','lipstick','lipliner','mascara','eyeliner'];if(!steps.includes(b.routine_step||''))fail('Invalid routine step.');
 const images=Array.isArray(b.images)?b.images.slice(0,8).filter(i=>i.url).map(i=>({url:imageUrl(i.url),alt_ar:text(i.alt_ar,500),alt_en:text(i.alt_en,500)})):[];
 const fields={name_ar:text(b.name_ar,500),name_en:text(b.name_en,500),short_description_ar:text(b.short_description_ar),short_description_en:text(b.short_description_en),details_ar:text(b.details_ar),details_en:text(b.details_en),slug:productSlug,sku:text(b.sku,100),category_id:categoryId,brand_id:brandId,selling_price:price,regular_price:regular,status:b.status,stock_status:b.stock_status,priority:priority(b.priority),routine_step:b.routine_step||null,seo_title_en:text(b.seo_title_en,100),seo_title_ar:text(b.seo_title_ar,100),seo_description_en:text(b.seo_description_en,300),seo_description_ar:text(b.seo_description_ar,300)};
 const client=await db.pool.connect();let productId;
 try{
 await client.query('BEGIN');
 const conflict=await client.query('SELECT id FROM products WHERE slug=$1 AND ($2::int IS NULL OR id<>$2)',[productSlug,req.params.id?id(req.params.id):null]);if(conflict.rows.length)fail('This product URL is already in use.',409);
 if(req.params.id){productId=id(req.params.id);const keys=Object.keys(fields),values=Object.values(fields);values.push(productId);const r=await client.query(`UPDATE products SET ${keys.map((k,i)=>k+'=$'+(i+1)).join(',')},translation_status='REVIEWED',updated_at=NOW() WHERE id=$${values.length} AND deleted_at IS NULL RETURNING id`,values);if(!r.rows.length)fail('Product not found',404);}
 else{const source='manual:'+crypto.randomUUID();Object.assign(fields,{source_url:source,source_identity_hash:crypto.createHash('sha256').update(source).digest('hex'),source_price:price,currency:'KWD',translation_status:b.name_en?'REVIEWED':'PENDING'});const r=await client.query(`INSERT INTO products(${Object.keys(fields).join(',')}) VALUES(${Object.keys(fields).map((_,i)=>'$'+(i+1)).join(',')}) RETURNING id`,Object.values(fields));productId=r.rows[0].id;}
 if(Array.isArray(b.images)){await client.query('DELETE FROM product_images WHERE product_id=$1',[productId]);for(let i=0;i<images.length;i++)await client.query('INSERT INTO product_images(product_id,cloudinary_url,image_order,width,height,source_filename,alt_ar,alt_en) VALUES($1,$2,$3,800,800,$4,$5,$6)',[productId,images[i].url,i+1,'admin-image-'+i,images[i].alt_ar,images[i].alt_en]);}
 await settings.audit(req.admin.id,'product.save',productId,{},client);await client.query('COMMIT');res.json({success:true,id:productId,slug:productSlug});
 }catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
}
router.post('/products',wrap(saveProduct));router.put('/products/:id',wrap(saveProduct));
router.get('/categories',wrap(async(req,res)=>res.json((await db.query('SELECT * FROM categories ORDER BY priority DESC,name_en')).rows)));
router.post('/categories',wrap(async(req,res)=>{const b=req.body;if(!text(b.name_ar)||!text(b.name_en))fail('Both category names are required.');const {rows}=await db.query('INSERT INTO categories(name_ar,name_en,slug,priority,status) VALUES($1,$2,$3,$4,$5) RETURNING *',[text(b.name_ar,255),text(b.name_en,255),slug(b.slug),priority(b.priority),'ACTIVE']);res.json(rows[0]);}));
router.put('/categories/:id',wrap(async(req,res)=>{const b=req.body;if(!text(b.name_ar)||!text(b.name_en)||!['ACTIVE','INACTIVE'].includes(b.status))fail('Invalid category.');const r=await db.query('UPDATE categories SET name_ar=$1,name_en=$2,priority=$3,status=$4,updated_at=NOW() WHERE id=$5 RETURNING id',[text(b.name_ar,255),text(b.name_en,255),priority(b.priority),b.status,id(req.params.id)]);if(!r.rows.length)fail('Category not found',404);await settings.audit(req.admin.id,'category.save',req.params.id);res.json({success:true});}));
router.get('/brands',wrap(async(req,res)=>res.json((await db.query('SELECT * FROM brands ORDER BY name')).rows)));
router.post('/brands',wrap(async(req,res)=>{if(!text(req.body.name))fail('Name required');const {rows}=await db.query('INSERT INTO brands(name,slug,status) VALUES($1,$2,\'ACTIVE\') RETURNING *',[text(req.body.name,255),slug(req.body.slug)]);res.json(rows[0]);}));
router.put('/brands/:id',wrap(async(req,res)=>{if(!text(req.body.name)||!['ACTIVE','INACTIVE'].includes(req.body.status))fail('Invalid brand');await db.query('UPDATE brands SET name=$1,status=$2,updated_at=NOW() WHERE id=$3',[text(req.body.name,255),req.body.status,id(req.params.id)]);res.json({success:true})}));
router.get('/offers',wrap(async(req,res)=>res.json((await db.query('SELECT * FROM offers ORDER BY priority DESC,id DESC')).rows)));
router.post('/offers',wrap(async(req,res)=>{
 const b=req.body,pct=Number(b.discount_percent);if(!text(b.title_en)||!text(b.title_ar)||!Number.isFinite(pct)||pct<=0||pct>90)fail('Supply both titles and a discount between 0 and 90%.');if(!b.product_id&&!b.category_id)fail('Choose a product or category.');
 const start=b.starts_at?new Date(b.starts_at):new Date(),end=b.ends_at?new Date(b.ends_at):null;if(!Number.isFinite(start.getTime())||(end&&(!Number.isFinite(end.getTime())||end<=start)))fail('Invalid offer dates.');
 const {rows}=await db.query('INSERT INTO offers(title_en,title_ar,discount_percent,product_id,category_id,starts_at,ends_at,priority,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true) RETURNING id',[text(b.title_en,200),text(b.title_ar,200),pct,b.product_id?id(b.product_id):null,b.category_id?id(b.category_id):null,start,end,priority(b.priority)]);await settings.audit(req.admin.id,'offer.create',rows[0].id);res.json(rows[0]);
}));
router.patch('/offers/:id',wrap(async(req,res)=>{if(typeof req.body.active!=='boolean')fail('Invalid offer status');await db.query('UPDATE offers SET active=$1 WHERE id=$2',[req.body.active,id(req.params.id)]);await settings.audit(req.admin.id,'offer.toggle',req.params.id);res.json({success:true});}));
router.get('/settings',wrap(async(req,res)=>{const result={};for(const key of ['delivery','payments','social','contact'])result[key]=await settings.getSettings(key);result.credentials=await settings.secretFlags();result.encryption_ready=/^[a-f0-9]{64}$/i.test(process.env.SETTINGS_ENCRYPTION_KEY||'');res.json(result);}));
router.put('/settings/:key',wrap(async(req,res)=>{
 const key=req.params.key,b=req.body;let value;
 if(key==='delivery'){const fee=Number(money(b.fee));const areas=Array.isArray(b.areas)?b.areas.slice(0,300).map(a=>({name_en:text(a.name_en,100),name_ar:text(a.name_ar,100),aliases:Array.isArray(a.aliases)?a.aliases.map(v=>text(v,100)).slice(0,5):[],fee:Number(money(a.fee))})):[];if(areas.some(a=>!a.name_en||!a.name_ar))fail('Both area names are required.');if(fee>3||areas.some(a=>a.fee>3))fail('Delivery fees cannot exceed 3 KWD.');const min=Number(b.estimate_min_days??1),max=Number(b.estimate_max_days??3);if(!Number.isInteger(min)||!Number.isInteger(max)||min<0||max<min||max>30)fail('Delivery estimate must be between 0 and 30 days');value={free_threshold:10,fee,enabled:b.enabled!==false,areas,require_area_match:b.require_area_match===true,estimate_min_days:min,estimate_max_days:max};}
 else if(key==='payments'){
 if(!['none','myfatoorah'].includes(b.provider)||!['sandbox','live'].includes(b.mode))fail('This provider adapter is not installed. Select MyFatoorah or leave online payment disconnected.');
 if(b.api_key)await settings.saveSecret('MYFATOORAH_API_KEY',text(b.api_key,4000));if(b.webhook_secret)await settings.saveSecret('MYFATOORAH_WEBHOOK_SECRET',text(b.webhook_secret,4000));
 if(b.enabled&&(b.provider==='none'||!await settings.getSecret('MYFATOORAH_API_KEY')||!await settings.getSecret('MYFATOORAH_WEBHOOK_SECRET')))fail('Save the API key and webhook secret before enabling online payments.');
 value={provider:b.provider,mode:b.mode,enabled:b.enabled===true,cod_enabled:b.cod_enabled===true};
 }else if(key==='translation'){if(!b.api_key)fail('API key required');await settings.saveSecret('GOOGLE_TRANSLATE_API_KEY',text(b.api_key,4000));return res.json({success:true});}
 else if(key==='social'){value={};const hosts={instagram:['instagram.com','www.instagram.com'],facebook:['facebook.com','www.facebook.com'],tiktok:['tiktok.com','www.tiktok.com'],snapchat:['snapchat.com','www.snapchat.com'],youtube:['youtube.com','www.youtube.com']};for(const [name,allowed]of Object.entries(hosts)){if(!b[name])continue;let u;try{u=new URL(b[name])}catch{fail('Invalid social URL')}if(u.protocol!=='https:'||!allowed.includes(u.hostname))fail('Invalid '+name+' URL');value[name]=u.origin+u.pathname;}}
 else if(key==='contact'){value={};for(const k of ['whatsapp','email','delivery_en','delivery_ar','returns_en','returns_ar'])value[k]=text(b[k],3000);if(value.whatsapp&&!/^965[24569]\d{7}$/.test(value.whatsapp))fail('WhatsApp should be 965 followed by 8 digits.');}
 else fail('Unknown settings section');
 await settings.setSettings(key,value);await settings.audit(req.admin.id,'settings.save',key);res.json({success:true});
}));
router.get('/customers',wrap(async(req,res)=>{const search='%'+text(req.query.search,100)+'%';const {rows}=await db.query(`SELECT c.id,c.name,c.email,c.phone,c.status,c.created_at,COUNT(o.id)::int AS order_count,COALESCE(SUM(o.total_amount) FILTER(WHERE o.status IN ('CONFIRMED','PROCESSING','READY_FOR_DELIVERY','OUT_FOR_DELIVERY','DELIVERED')),0) AS total_spend FROM customers c LEFT JOIN orders o ON o.customer_id=c.id WHERE c.email ILIKE $1 OR c.name ILIKE $1 GROUP BY c.id ORDER BY c.id DESC LIMIT 100`,[search]);res.json(rows);}));
router.get('/customers/:id',wrap(async(req,res)=>{const customer=(await db.query('SELECT id,name,email,phone,status,created_at FROM customers WHERE id=$1',[id(req.params.id)])).rows[0];if(!customer)fail('Customer not found',404);const orders=(await db.query('SELECT order_number,total_amount,status,created_at FROM orders WHERE customer_id=$1 ORDER BY id DESC LIMIT 100',[customer.id])).rows;res.json({customer,orders});}));
router.get('/dashboard',wrap(async(req,res)=>{
 const products=(await db.query("SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='ACTIVE' AND stock_status='IN_STOCK')::int AS live,COUNT(*) FILTER(WHERE translation_status='PENDING')::int AS untranslated FROM products WHERE deleted_at IS NULL")).rows[0];
 const orders=(await db.query("SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='CONFIRMED')::int AS confirmed,COALESCE(SUM(total_amount) FILTER(WHERE status IN ('CONFIRMED','PROCESSING','READY_FOR_DELIVERY','OUT_FOR_DELIVERY','DELIVERED')),0) AS sales FROM orders")).rows[0];
 const issues=[products.untranslated?`${products.untranslated} products need English translation.`:null,!(await settings.getSettings('payments')).enabled?'Online payment is not connected. Cash on delivery can operate independently.':null,!(await settings.getSettings('delivery')).areas?.length?'Configure nearby and remote delivery areas.':null].filter(Boolean);res.json({products,orders,issues});
}));
router.get('/posts',wrap(async(req,res)=>res.json((await db.query('SELECT * FROM blog_posts ORDER BY id DESC LIMIT 100')).rows)));
async function savePost(req,res){const b=req.body;if(!text(b.title_en)||!text(b.title_ar)||!text(b.body_en)||!text(b.body_ar))fail('Supply English and Arabic titles and article text.');if(!['DRAFT','PUBLISHED'].includes(b.status))fail('Invalid post status');const publish=b.publish_at?new Date(b.publish_at):null;if(publish&&!Number.isFinite(publish.getTime()))fail('Invalid publication date');if(b.status==='PUBLISHED'&&!publish)fail('Choose a publication date.');const fields={slug:slug(b.slug),title_en:text(b.title_en,200),title_ar:text(b.title_ar,200),excerpt_en:text(b.excerpt_en,300),excerpt_ar:text(b.excerpt_ar,300),body_en:text(b.body_en,40000),body_ar:text(b.body_ar,40000),image_url:require('../services/media').validateUrl(b.image_url),image_alt_en:text(b.image_alt_en,500),image_alt_ar:text(b.image_alt_ar,500),status:b.status,publish_at:publish};let result;if(req.params.id){const values=Object.values(fields);values.push(id(req.params.id));result=await db.query(`UPDATE blog_posts SET ${Object.keys(fields).map((k,i)=>k+'=$'+(i+1)).join(',')},updated_at=NOW() WHERE id=$${values.length} RETURNING id`,values);}else result=await db.query(`INSERT INTO blog_posts(${Object.keys(fields).join(',')}) VALUES(${Object.keys(fields).map((_,i)=>'$'+(i+1)).join(',')}) RETURNING id`,Object.values(fields));if(!result.rows.length)fail('Article not found',404);res.json(result.rows[0]);}
router.post('/posts',wrap(savePost));router.put('/posts/:id',wrap(savePost));
router.get('/returns',wrap(async(req,res)=>res.json((await db.query('SELECT r.*,o.order_number FROM return_requests r JOIN orders o ON o.id=r.order_id ORDER BY r.id DESC LIMIT 100')).rows)));
router.patch('/returns/:id',wrap(async(req,res)=>{if(!['APPROVED','REJECTED','RECEIVED','CLOSED'].includes(req.body.status))fail('Invalid return status');const client=await db.pool.connect();try{await client.query('BEGIN');const r=(await client.query('SELECT * FROM return_requests WHERE id=$1 FOR UPDATE',[id(req.params.id)])).rows[0];if(!r)fail('Return not found',404);const transitions={REQUESTED:['APPROVED','REJECTED'],APPROVED:['RECEIVED'],RECEIVED:['CLOSED']};if(!transitions[r.status]?.includes(req.body.status))fail('Invalid return transition',409);await client.query('UPDATE return_requests SET status=$1,admin_note=$2,updated_at=NOW() WHERE id=$3',[req.body.status,text(req.body.admin_note,1000),r.id]);await client.query('INSERT INTO return_history(return_id,status,note,admin_id) VALUES($1,$2,$3,$4)',[r.id,req.body.status,text(req.body.admin_note,1000),req.admin.id]);if(req.body.status==='RECEIVED'){const order=(await client.query('SELECT status FROM orders WHERE id=$1 FOR UPDATE',[r.order_id])).rows[0];const purchased=(await client.query('SELECT product_id,SUM(quantity)::int quantity FROM order_items WHERE order_id=$1 GROUP BY product_id',[r.order_id])).rows;const received=(await client.query("SELECT items FROM return_requests WHERE order_id=$1 AND status IN ('RECEIVED','CLOSED')",[r.order_id])).rows.flatMap(x=>x.items||[]);const full=purchased.every(i=>received.filter(x=>x.product_id===i.product_id).reduce((sum,x)=>sum+Number(x.quantity),0)>=i.quantity);const nextStatus=full?'RETURNED':order.status;if(full)await client.query("UPDATE orders SET status='RETURNED',updated_at=NOW() WHERE id=$1",[r.order_id]);await client.query('INSERT INTO order_status_history(order_id,old_status,new_status,reason,changed_by_admin_id) VALUES($1,$2,$3,$4,$5)',[r.order_id,order.status,nextStatus,full?'Return received':'Partial return received',req.admin.id]);}await settings.audit(req.admin.id,'return.'+req.body.status,r.id,{},client);await client.query('COMMIT');res.json({success:true});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}));
router.get('/orders/:number/cash',wrap(async(req,res)=>res.json((await db.query('SELECT t.id,t.kind,t.amount,t.note,t.created_at FROM cash_transactions t JOIN orders o ON o.id=t.order_id WHERE o.order_number=$1 ORDER BY t.id',[req.params.number])).rows)));
router.post('/orders/:number/cash',wrap(async(req,res)=>{const b=req.body;if(!['COLLECTION','REFUND'].includes(b.kind)||!text(b.note)||!/^[a-zA-Z0-9-]{20,100}$/.test(b.idempotency_key||''))fail('Provide the transaction type, reference/note and request key.');const amount=Number(money(b.amount));if(amount<=0)fail('Amount must be positive.');const client=await db.pool.connect();try{await client.query('BEGIN');const order=(await client.query('SELECT * FROM orders WHERE order_number=$1 FOR UPDATE',[req.params.number])).rows[0];if(!order||order.payment_method!=='COD')fail('Cash-on-delivery order not found.',404);const prior=(await client.query('SELECT * FROM cash_transactions WHERE idempotency_key=$1',[b.idempotency_key])).rows[0];if(prior){if(prior.order_id!==order.id||prior.kind!==b.kind||Number(prior.amount)!==amount)fail('This request key was used for different details.',409);await client.query('COMMIT');return res.json({success:true,id:prior.id});}const totals=(await client.query("SELECT COALESCE(SUM(amount) FILTER(WHERE kind='COLLECTION'),0) collected,COALESCE(SUM(amount) FILTER(WHERE kind='REFUND'),0) refunded FROM cash_transactions WHERE order_id=$1",[order.id])).rows[0];if(b.kind==='COLLECTION'){if(!['OUT_FOR_DELIVERY','DELIVERED'].includes(order.status)||Number(totals.collected)>0||amount!==Number(order.total_amount))fail('Record the full order amount once, after dispatch.',409);}else if(Math.round(amount*1000)>Math.round((Number(totals.collected)-Number(totals.refunded))*1000))fail('Refund exceeds the cash collected.',409);const row=(await client.query('INSERT INTO cash_transactions(order_id,kind,amount,note,admin_id,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[order.id,b.kind,amount,text(b.note,1000),req.admin.id,b.idempotency_key])).rows[0];await settings.audit(req.admin.id,'cash.'+b.kind,order.id,{amount},client);await client.query('COMMIT');res.json({success:true,id:row.id});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}));
router.use('/translations',require('./translations'));
module.exports=router;
