const router=require('express').Router(),db=require('../db'),catalog=require('../services/catalog');
const {shell,homeContent,esc,origin}=require('../views/storefront');const {pages,policyContent}=require('../views/policies');
const {schema}=require('../services/site-identity');
const {journalMarkup}=require('../services/journal-markup');
const discovery=require('../services/search-discovery');
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const localized=(kind,slug)=>Object.fromEntries(['ar','en'].map(l=>[l,origin+'/'+l+(kind?'/'+kind+'/'+encodeURIComponent(slug):'/')]));
function productCard(p,l){const n=p['name_'+l]||p.name_ar||'Mikyaj';return `<article class="product-card"><a href="/${l}/products/${encodeURIComponent(p.slug)}">${p.primary_image?.url?`<img src="${esc(p.primary_image.url.replace('/image/upload/','/image/upload/f_auto,q_auto,c_limit,w_480/'))}" srcset="${[240,480,800].map(w=>esc(p.primary_image.url.replace('/image/upload/','/image/upload/f_auto,q_auto,c_limit,w_'+w+'/'))+' '+w+'w').join(', ')}" sizes="(max-width: 767px) 44vw, 280px" alt="${esc(p.primary_image['alt_'+l]||n)}" width="480" height="480" loading="lazy">`:''}<h3>${esc(n)}</h3><p>${Number(p.selling_price).toFixed(3)} KWD</p></a></article>`}
router.get('/robots.txt',(req,res)=>res.type('text/plain').send(discovery.robots()));
function sendXml(res,body){return res.set('Cache-Control','public,max-age=0,must-revalidate').type('application/xml').send(body)}
router.get('/sitemap.xml',(req,res)=>sendXml(res,discovery.sitemapIndex()));
router.get('/sitemap-pages.xml',(req,res)=>sendXml(res,discovery.pageSitemap()));
for(const [kind,sql]of [
 ['products',"SELECT p.slug,p.updated_at FROM products p JOIN categories c ON c.id=p.category_id WHERE p.status='ACTIVE' AND c.status='ACTIVE' AND p.deleted_at IS NULL AND p.slug IS NOT NULL AND p.slug<>'' ORDER BY p.id"],
 ['categories',"SELECT slug,updated_at FROM categories WHERE status='ACTIVE' AND slug IS NOT NULL AND slug<>'' ORDER BY id"],
 ['journal',"SELECT slug,updated_at FROM blog_posts WHERE status='PUBLISHED' AND publish_at<=NOW() AND slug IS NOT NULL AND slug<>'' ORDER BY id"]
])router.get('/sitemap-'+kind+'.xml',wrap(async(req,res)=>{
 const result=await db.query(sql);
 sendXml(res,discovery.urlset(result.rows.map(row=>({alternates:discovery.localized(kind,row.slug),updated_at:row.updated_at}))));
}));
router.get(['/','/index.html','/ar/','/en/'],wrap(async(req,res)=>{const l=req.path.startsWith('/en')||req.query.lang==='en'?'en':'ar';const data=await catalog.listProducts({limit:8});const banners=await require('../services/storefront-banners').publicBanners();const content=homeContent(l,await require('../services/commerce-settings').getSettings('homepage'),banners).replace('<div id="homeProducts"></div>',`<div id="homeProducts"><div class="product-grid">${data.products.map(p=>productCard(p,l)).join('')}</div></div>`);res.set('Cache-Control','public,max-age=0,must-revalidate').send(shell({lang:l,content,description:banners.find(b=>b.placement==='hero')?.['seo_description_'+l]||undefined,robots:req.query.content_admin==='1'?'noindex,nofollow':'index,follow',canonical:localized()[l],alternates:localized(),initial:{products:data.products},structured:schema()}))}));
router.get('/product.html',wrap(async(req,res,next)=>{if(!req.query.slug)return next();const p=await catalog.product(String(req.query.slug));if(!p)return next();res.redirect(301,'/'+(req.query.lang==='en'?'en':'ar')+'/products/'+encodeURIComponent(p.slug))}));
router.get('/shop.html',wrap(async(req,res)=>{const l=req.query.lang==='en'?'en':'ar';const filtered=Object.keys(req.query).some(k=>k!=='lang');const data=await catalog.listProducts({search:req.query.q,category:req.query.category||req.query.cat,sort:req.query.sort,offers:req.query.offers,brand:req.query.brand,min_price:req.query.min_price,max_price:req.query.max_price});const title=l==='ar'?'تسوقي المكياج والعناية بالبشرة في الكويت':'Shop makeup and skincare in Kuwait';res.send(shell({page:'shop',lang:l,title,initial:{products:data.products,next_cursor:data.next_cursor},robots:filtered?'noindex,follow':'index,follow',canonical:origin+'/shop.html?lang='+l,alternates:{ar:origin+'/shop.html?lang=ar',en:origin+'/shop.html?lang=en'},content:`<div class="container section"><h1>${title}</h1><div class="product-grid">${data.products.map(p=>productCard(p,l)).join('')}</div></div>`}))}));
router.get('/blog.html',wrap(async(req,res)=>{const l=req.query.lang==='en'?'en':'ar',posts=(await db.query("SELECT * FROM blog_posts WHERE status='PUBLISHED' AND publish_at<=NOW() ORDER BY publish_at DESC LIMIT 30")).rows;const title=l==='ar'?'دليل الجمال في الكويت':'The beauty journal · Kuwait';res.send(shell({page:'blog',lang:l,title,canonical:origin+'/blog.html?lang='+l,alternates:{ar:origin+'/blog.html?lang=ar',en:origin+'/blog.html?lang=en'},content:`<div class="container section"><h1>${title}</h1>${posts.map(p=>`<article><h2><a href="/${l}/journal/${esc(p.slug)}">${esc(p['title_'+l])}</a></h2><p>${esc(p['excerpt_'+l])}</p></article>`).join('')}</div>`}))}));
router.get('/:lang/products/:slug',wrap(async(req,res,next)=>{const l=req.params.lang;if(!['ar','en'].includes(l))return next();const p=await catalog.product(req.params.slug);if(!p)return next();const n=p['name_'+l]||p.name_ar;const desc=p['seo_description_'+l]||p['short_description_'+l]||`${n} — Mikyaj Kuwait`;const canonical=localized('products',p.slug);const structured={'@context':'https://schema.org','@type':'Product',name:n,description:desc,sku:p.sku||String(p.id),image:p.images.map(i=>i.url),...(p.brand?{brand:{'@type':'Brand',name:p.brand.name}}:{}),offers:{'@type':'Offer',url:canonical[l],priceCurrency:'KWD',price:p.selling_price,availability:'https://schema.org/'+(p.stock_status==='IN_STOCK'?'InStock':'OutOfStock'),itemCondition:'https://schema.org/NewCondition'}};const img=p.images[0];res.send(shell({page:'product',lang:l,title:p['seo_title_'+l]||n,description:desc,canonical:canonical[l],alternates:canonical,initial:{product:p},structured,content:`<article class="container section product-layout"><div>${img?`<img src="${esc(img.url.replace('/image/upload/','/image/upload/f_auto,q_auto,c_limit,w_800/'))}" alt="${esc(img['alt_'+l]||n)}" width="800" height="800" fetchpriority="high">`:''}</div><div><h1>${esc(n)}</h1><p>${Number(p.selling_price).toFixed(3)} KWD</p><p>${esc(p.content_sections[l].description)}</p><p style="white-space:pre-line">${esc(p.content_sections[l].details)}</p><details open class="product-directions"><summary>${l==='ar'?'طريقة الاستخدام':'How to use'}</summary><p style="white-space:pre-line">${esc(p.content_sections[l].how_to_use||(l==='ar'?'لم تتوفر تعليمات خاصة بهذا المنتج بعد. اتبعي تعليمات الاستخدام والتحذيرات على العبوة، أو تواصلي مع فريقنا للمساعدة.':'Product-specific directions have not yet been provided. Follow the instructions and warnings on the packaging, or contact our team for help.'))}</p></details></div></article>`}))}));
router.get('/:lang/categories/:slug',wrap(async(req,res,next)=>{const l=req.params.lang;if(!['ar','en'].includes(l))return next();const c=(await db.query("SELECT * FROM categories WHERE slug=$1 AND status='ACTIVE'",[req.params.slug])).rows[0];if(!c)return next();const data=await catalog.listProducts({category:c.slug});const alts=localized('categories',c.slug);res.send(shell({page:'shop',lang:l,title:c['name_'+l]+' · '+(l==='ar'?'الكويت':'Kuwait'),canonical:alts[l],alternates:alts,initial:{category:c,products:data.products,next_cursor:data.next_cursor},content:`<div class="container section"><h1>${esc(c['name_'+l])}</h1><div class="product-grid">${data.products.map(p=>productCard(p,l)).join('')}</div></div>`}))}));
router.get('/:lang/journal/:slug',wrap(async(req,res,next)=>{const l=req.params.lang;if(!['ar','en'].includes(l))return next();const p=(await db.query("SELECT * FROM blog_posts WHERE slug=$1 AND status='PUBLISHED' AND publish_at<=NOW()",[req.params.slug])).rows[0];if(!p)return next();const alts=localized('journal',p.slug);res.send(shell({page:'article',lang:l,title:p['title_'+l],description:p['excerpt_'+l],canonical:alts[l],alternates:alts,initial:{post:p},structured:{'@context':'https://schema.org','@type':'BlogPosting',headline:p['title_'+l],datePublished:new Date(p.publish_at).toISOString(),dateModified:new Date(p.updated_at).toISOString(),author:{'@type':'Organization',name:'Mikyaj'},mainEntityOfPage:alts[l],...(p.image_url?{image:p.image_url}:{})},content:`<article class="container section prose"><h1>${esc(p['title_'+l])}</h1>${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p['image_alt_'+l]||p['title_'+l])}" width="640" height="640">`:''}${journalMarkup(p['body_'+l])}</article>`}))}));
for(const [page,p]of Object.entries(pages))router.get('/'+page+'.html',(req,res)=>{const l=req.query.lang==='en'?'en':'ar';res.send(shell({page,lang:l,title:p.title[l==='ar'?1:0],description:p.sections[0][l==='ar'?3:2].slice(0,160),canonical:origin+'/'+page+'.html?lang='+l,alternates:{ar:origin+'/'+page+'.html?lang=ar',en:origin+'/'+page+'.html?lang=en'},content:policyContent(page,l),initial:{policy:{ar:policyContent(page,'ar'),en:policyContent(page,'en')}}}))});
router.get('/brands.html',wrap(async(req,res)=>{
 const l=req.query.lang==='en'?'en':'ar';const brands=(await db.query("SELECT b.id,b.name,b.slug,COUNT(p.id)::int AS product_count FROM brands b JOIN products p ON p.brand_id=b.id AND p.status='ACTIVE' AND p.deleted_at IS NULL JOIN categories c ON c.id=p.category_id AND c.status='ACTIVE' WHERE b.status='ACTIVE' GROUP BY b.id ORDER BY b.name")).rows;
 const title=l==='ar'?'تسوقي حسب الماركة':'Shop by brand';res.send(shell({page:'brands',lang:l,title,canonical:origin+'/brands.html?lang='+l,alternates:{ar:origin+'/brands.html?lang=ar',en:origin+'/brands.html?lang=en'},content:`<div class="container section"><h1>${title}</h1><div class="brand-grid">${brands.map(b=>`<a class="brand-tile" href="/shop.html?lang=${l}&amp;brand=${encodeURIComponent(b.slug)}"><strong>${esc(b.name)}</strong><span>${b.product_count}</span></a>`).join('')}</div></div>`}));
}));
module.exports=router;
