const router=require('express').Router();const db=require('../db');const crypto=require('node:crypto');const catalog=require('../services/catalog');const {getSettings}=require('../services/commerce-settings');const {quote,fail,GOVERNORATES}=require('../services/commerce-quote');
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
router.get('/config',wrap(async(req,res)=>{const delivery=await getSettings('delivery'),payments=await getSettings('payments'),social=await getSettings('social'),contact=await getSettings('contact');res.json({delivery,payments:{cod_enabled:payments.cod_enabled,online_enabled:payments.enabled&&payments.provider!=='none',provider:payments.provider,mode:payments.mode},social,contact,governorates:GOVERNORATES});}));
router.post('/quote',wrap(async(req,res)=>{res.set('Cache-Control','no-store');res.json(await quote(req.body.items,undefined,req.body.area));}));
router.get('/recommendations',wrap(async(req,res)=>{res.set('Cache-Control','private, no-store');res.json({products:await catalog.recommendations(String(req.query.ids||'').split(','),req.customer?.id)});}));
router.post('/bag-products',wrap(async(req,res)=>{if(!Array.isArray(req.body.ids)||req.body.ids.length>100)fail('Invalid product list');res.set('Cache-Control','no-store');res.json({products:await catalog.byIds(req.body.ids.map(Number).filter(n=>Number.isSafeInteger(n)&&n>0))});}));
router.get('/posts',wrap(async(req,res)=>res.json((await db.query("SELECT id,slug,title_ar,title_en,excerpt_ar,excerpt_en,image_url,image_alt_ar,image_alt_en,publish_at FROM blog_posts WHERE status='PUBLISHED' AND publish_at<=NOW() ORDER BY publish_at DESC LIMIT 30")).rows)));
router.get('/posts/:slug',wrap(async(req,res)=>{const post=(await db.query("SELECT * FROM blog_posts WHERE slug=$1 AND status='PUBLISHED' AND publish_at<=NOW()",[req.params.slug])).rows[0];if(!post)fail('Article not found',404);res.json({post});}));
async function ownedOrder(req){const {rows}=await db.query('SELECT * FROM orders WHERE order_number=$1',[req.params.number]);const o=rows[0];if(!o)fail('Order not found',404);if(req.customer?.id===o.customer_id)return o;const token=String(req.headers['x-order-token']||'');const hash=crypto.createHash('sha256').update(token).digest('hex');if(!o.tracking_token_hash||!token||!crypto.timingSafeEqual(Buffer.from(hash),Buffer.from(o.tracking_token_hash)))fail('Order not found',404);return o;}
router.get('/orders/:number',wrap(async(req,res)=>{res.set('Cache-Control','no-store');const o=await ownedOrder(req);const items=(await db.query('SELECT product_id,quantity,price_at_purchase,product_name_ar,product_name_en FROM order_items WHERE order_id=$1',[o.id])).rows;const history=(await db.query('SELECT new_status,created_at FROM order_status_history WHERE order_id=$1 ORDER BY id',[o.id])).rows;const returns=(await db.query('SELECT id,status,reason,created_at FROM return_requests WHERE order_id=$1 ORDER BY id DESC',[o.id])).rows;const cash=(await db.query("SELECT COALESCE(SUM(amount) FILTER(WHERE kind='COLLECTION'),0) collected,COALESCE(SUM(amount) FILTER(WHERE kind='REFUND'),0) refunded FROM cash_transactions WHERE order_id=$1",[o.id])).rows[0];const payment=(await db.query('SELECT status FROM payments WHERE order_id=$1 ORDER BY id DESC LIMIT 1',[o.id])).rows[0];res.json({order:{order_number:o.order_number,status:o.status,total_amount:o.total_amount,subtotal:o.subtotal,delivery_fee:o.delivery_fee,payment_method:o.payment_method,payment_status:o.payment_method==='COD'?(Number(cash.refunded)>=Number(o.total_amount)?'REFUNDED':Number(cash.refunded)>0?'PARTIALLY_REFUNDED':Number(cash.collected)>0?'COLLECTED':'UNPAID'):payment?.status||'UNPAID',created_at:o.created_at},items,history,returns});}));
router.post('/orders/:number/return',wrap(async(req,res)=>{const o=await ownedOrder(req);if(o.status!=='DELIVERED')fail('A return can be requested after delivery.',409);const reason=String(req.body.reason||'').trim();if(reason.length<5||reason.length>2000)fail('Describe the reason for your return.');await db.query("INSERT INTO return_requests(order_id,reason) VALUES($1,$2)",[o.id,reason]);res.status(201).json({success:true});}));
module.exports=router;
