const {esc}=require('./storefront');
const pages={
 terms:{title:['Terms and conditions','الشروط والأحكام'],sections:[
 ['Shopping with Mikyaj','التسوق من ميكاج','These terms apply to purchases from mikyajkw.com for delivery within Kuwait. For order questions, cancellations or complaints, contact +965 6623 2231 by phone or WhatsApp.','تسري هذه الشروط على المشتريات من mikyajkw.com للتوصيل داخل الكويت. للاستفسار عن الطلبات أو الإلغاء أو الشكاوى، تواصلي معنا عبر الهاتف أو واتساب على 6623 2231 965+.'],
 ['Products and prices','المنتجات والأسعار','Prices and checkout totals are in Kuwaiti dinars (KWD). Product availability, active offers and delivery charges are checked when an order is placed. Product images illustrate the item; screen colours may differ. Arabic product information is the source for translated descriptions. Contact us if any detail is unclear before ordering.','الأسعار وإجمالي الطلب بالدينار الكويتي. يتم التحقق من توفر المنتجات والعروض ورسوم التوصيل عند تأكيد الطلب. صور المنتجات توضيحية وقد تختلف الألوان حسب الشاشة. تعتمد الترجمات على معلومات المنتج العربية. تواصلي معنا قبل الطلب إذا كان أي تفصيل غير واضح.'],
 ['Orders and payment','الطلبات والدفع','Provide accurate contact and delivery details. A confirmed cash-on-delivery order is payable on arrival. Online payment is available only when shown at checkout; a redirect alone does not confirm payment. We may contact you about unavailable items or errors and will explain any proposed change before proceeding. If we cannot fulfil a paid order, the amount due back will be refunded.','يرجى تقديم بيانات اتصال وتوصيل صحيحة. تُدفع قيمة طلب الدفع عند الاستلام عند وصوله. يتوفر الدفع الإلكتروني فقط عندما يظهر في صفحة إتمام الطلب، ولا يؤكد الانتقال إلى صفحة الدفع نجاح العملية. قد نتواصل معك بشأن المنتجات غير المتوفرة أو الأخطاء، ونوضح أي تعديل مقترح قبل المتابعة. إذا تعذر تنفيذ طلب مدفوع، تتم إعادة المبلغ المستحق.'],
 ['Cancellation and returns','الإلغاء والإرجاع','Contact support as soon as possible to request cancellation. Once an order is dispatched, support will explain the available return options. See the Returns page for the process. These terms do not remove statutory consumer rights under applicable Kuwait law.','لطلب الإلغاء، تواصلي مع الدعم في أقرب وقت. إذا تم شحن الطلب، سيشرح الدعم خيارات الإرجاع المتاحة. راجعي صفحة الإرجاع لمعرفة الخطوات. لا تنتقص هذه الشروط من حقوق المستهلك المقررة بموجب القوانين الكويتية المعمول بها.'],
 ['Responsible use','الاستخدام المسؤول','Keep account passwords and private tracking links secure. Use products according to the manufacturer’s directions and product label. Website content does not replace individual professional advice. Changes to these terms apply to future orders; the terms shown when you place an order apply to that order.','حافظي على سرية كلمة المرور وروابط تتبع الطلبات الخاصة. استخدمي المنتجات وفق تعليمات الشركة المصنّعة والملصق. محتوى الموقع لا يحل محل المشورة المهنية الشخصية. تطبق تحديثات الشروط على الطلبات المستقبلية، وتسري على طلبك الشروط المعروضة وقت تقديمه.']
 ]},
 privacy:{title:['Privacy policy','سياسة الخصوصية'],sections:[
 ['Information we use','المعلومات التي نستخدمها','We use the name, phone number, email, delivery address and order details you provide to process purchases, deliver orders, respond to requests and maintain transaction records. If you create an account, we store a password hash rather than your readable password. Technical request logs may contain IP addresses and device information for security and troubleshooting.','نستخدم الاسم ورقم الهاتف والبريد الإلكتروني وعنوان التوصيل وتفاصيل الطلب التي تقدمينها لتنفيذ المشتريات والتوصيل والرد على الطلبات وحفظ سجلات المعاملات. عند إنشاء حساب، نخزن بصمة مشفرة لكلمة المرور بدلاً من نصها المقروء. قد تتضمن السجلات التقنية عنوان الإنترنت ومعلومات الجهاز لأغراض الأمان وحل المشكلات.'],
 ['Who receives information','من يتلقى المعلومات','Order details needed for fulfilment may be shared with delivery workers. Hosting, image delivery and email providers process information needed to operate the store. When online payment is enabled, the selected payment provider processes payment details on its payment page; do not send card details to store support. We do not sell customer information.','قد تتم مشاركة تفاصيل الطلب اللازمة للتوصيل مع عمال التوصيل. يعالج مزودو الاستضافة والصور والبريد الإلكتروني المعلومات اللازمة لتشغيل المتجر. عند تفعيل الدفع الإلكتروني، يعالج مزود الدفع المختار بيانات الدفع في صفحته؛ لا ترسلي بيانات البطاقة إلى الدعم. لا نبيع معلومات العملاء.'],
 ['Cookies and browser storage','ملفات الارتباط وتخزين المتصفح','An essential session cookie keeps you signed in. Browser storage remembers your language, bag, wishlist and private order tracking tokens. These features do not require advertising cookies. Clear browser data to remove these local preferences; doing so may remove guest order access from that browser. Contact support to recover assistance with an order.','يستخدم ملف ارتباط أساسي للحفاظ على تسجيل الدخول. يحفظ المتصفح اللغة والحقيبة والمفضلة ورموز تتبع الطلبات الخاصة. لا تتطلب هذه الميزات ملفات إعلانية. يمكنك مسح بيانات المتصفح لإزالة التفضيلات المحلية؛ وقد يؤدي ذلك إلى فقدان الوصول المحلي لطلبات الزائرة. تواصلي مع الدعم للمساعدة بشأن طلبك.'],
 ['Retention and your requests','الاحتفاظ بالبيانات وطلباتك','We retain transaction information as needed for fulfilment, returns, disputes and applicable recordkeeping obligations. Contact +965 6623 2231 to request access, correction or deletion of your information. We may need to verify your identity and retain records that applicable law requires. External links, including Instagram and WhatsApp, follow those services’ own privacy practices.','نحتفظ بمعلومات المعاملات حسب الحاجة لتنفيذ الطلبات والإرجاع وتسوية النزاعات والالتزامات النظامية لحفظ السجلات. لطلب الاطلاع على معلوماتك أو تصحيحها أو حذفها، تواصلي على 6623 2231 965+. قد نحتاج للتحقق من هويتك والاحتفاظ بالسجلات المطلوبة قانوناً. تخضع الروابط الخارجية، بما فيها إنستغرام وواتساب، لسياسات تلك الخدمات.']
 ]},
 returns:{title:['Returns and cancellations','الإرجاع والإلغاء'],sections:[
 ['How to request help','كيفية طلب المساعدة','Call or WhatsApp +965 6623 2231 with your order number, the product concerned and the reason. For delivered orders, you can also request a return from the order tracking page. Keep the invoice, packaging and included accessories while your request is reviewed. Please do not send a return before receiving collection or drop-off instructions.','اتصلي أو راسلينا عبر واتساب على 6623 2231 965+ مع رقم الطلب واسم المنتج وسبب الطلب. يمكنك أيضاً تقديم طلب إرجاع للطلبات المستلمة من صفحة التتبع. احتفظي بالفاتورة والتغليف والملحقات أثناء مراجعة الطلب. يرجى عدم إرسال المرتجع قبل استلام تعليمات التسليم أو الاستلام.'],
 ['Eligibility','أهلية الإرجاع','Kuwait consumer-protection rules generally provide a 14-day return or exchange period for goods in their original condition, subject to applicable product-specific exceptions. Perfumes and other categories may have different requirements. Eligibility for opened or used cosmetics depends on the product, its condition and the reason for return; statutory rights for defective, damaged or incorrect goods remain applicable. Contact us promptly so we can explain the rule relevant to your item.','تنص قواعد حماية المستهلك في الكويت عموماً على فترة 14 يوماً للإرجاع أو الاستبدال للسلع بحالتها الأصلية، مع مراعاة الاستثناءات الخاصة ببعض المنتجات. قد تختلف الشروط للعطور وغيرها من الفئات. تعتمد أهلية مستحضرات التجميل المفتوحة أو المستخدمة على المنتج وحالته وسبب الإرجاع، مع بقاء الحقوق القانونية المتعلقة بالعيوب أو التلف أو السلع غير المطابقة. تواصلي معنا سريعاً لتوضيح الشروط الخاصة بمنتجك.'],
 ['Damaged, incorrect or incomplete orders','الطلبات التالفة أو غير الصحيحة أو الناقصة','Contact us promptly with the order number and, if possible, photos of the product and packaging. Do not use a product that appears damaged or tampered with. Support will arrange the appropriate resolution after reviewing the issue.','تواصلي معنا سريعاً مع رقم الطلب وصور المنتج والتغليف إن أمكن. لا تستخدمي منتجاً يبدو تالفاً أو مفتوحاً بطريقة غير طبيعية. سيقوم الدعم بترتيب الحل المناسب بعد مراجعة المشكلة.'],
 ['Refunds and collection','استرداد المبالغ واستلام المرتجعات','Once a return is accepted and checked, support will confirm the refund amount, collection arrangements and any lawful collection charge before proceeding. Online-payment refunds normally go to the original payment method, subject to provider processing time. Cash-on-delivery refunds are arranged directly with support. A return status update is not itself proof that a refund has been paid.','بعد قبول المرتجع وفحصه، يؤكد الدعم مبلغ الاسترداد وترتيبات الاستلام وأي رسوم استلام جائزة قبل المتابعة. تُعاد مبالغ الدفع الإلكتروني عادة إلى وسيلة الدفع الأصلية وفق مدة معالجة المزود. يتم ترتيب استرداد طلبات الدفع النقدي مباشرة مع الدعم. تحديث حالة الإرجاع لا يعني بحد ذاته صرف مبلغ الاسترداد.']
 ]},
 delivery:{title:['Delivery in Kuwait','التوصيل داخل الكويت'],sections:[
 ['Delivery charges','رسوم التوصيل','Delivery is free when your product subtotal after discounts is 10.000 KWD or more. Below 10 KWD, delivery is calculated by your area and shown before you place the order. Nearby areas are 1 KWD; farther areas can be 2 or 3 KWD. The selected area must match the actual delivery address.','التوصيل مجاني عندما يبلغ مجموع المنتجات بعد الخصومات 10.000 د.ك أو أكثر. للطلبات الأقل من 10 د.ك، تُحسب الرسوم حسب المنطقة وتظهر قبل تأكيد الطلب. رسوم المناطق القريبة 1 د.ك، وقد تبلغ للمناطق الأبعد 2 أو 3 د.ك. يجب أن تتطابق المنطقة المختارة مع عنوان التوصيل الفعلي.'],
 ['Receiving your order','استلام طلبك','Enter your governorate, area, block, street, building and a reachable Kuwait phone number. Local delivery workers handle deliveries. Support will coordinate delivery; no same-day or fixed arrival time is promised unless confirmed directly for your order. Track confirmation, preparation, dispatch and delivery through your account or private tracking link.','أدخلي المحافظة والمنطقة والقطعة والشارع والمبنى ورقم هاتف كويتي يمكن الوصول إليه. يتولى عمال توصيل محليون تنفيذ الطلبات. ينسق الدعم موعد التوصيل؛ ولا يُضمن التوصيل في اليوم نفسه أو في وقت محدد إلا إذا تم تأكيد ذلك مباشرة لطلبك. تابعي التأكيد والتجهيز والشحن والتسليم من حسابك أو رابط التتبع الخاص.'],
 ['Address changes and missed delivery','تغيير العنوان وتعذر التسليم','Contact +965 6623 2231 promptly if your address changes or you will be unavailable. Any change to delivery charges will be explained before you agree to it. If your area is missing at checkout, contact support to confirm service.','إذا تغير عنوانك أو تعذر وجودك للاستلام، تواصلي سريعاً على 6623 2231 965+. سيتم توضيح أي تغيير في رسوم التوصيل قبل موافقتك عليه. إذا لم تظهر منطقتك عند إتمام الطلب، تواصلي مع الدعم للتأكد من إمكانية التوصيل.']
 ]},
 contact:{title:['We’re here to help','نحن هنا لمساعدتك'],sections:[['Order and product support','دعم الطلبات والمنتجات','For product questions, delivery, returns or order support, call +965 6623 2231 or send us a WhatsApp message. Include your order number when asking about an existing order. Never send passwords or card details.','للاستفسار عن المنتجات أو التوصيل أو الإرجاع أو الطلبات، اتصلي على 6623 2231 965+ أو أرسلي رسالة واتساب. يرجى ذكر رقم الطلب عند الاستفسار عن طلب سابق. لا ترسلي كلمات المرور أو بيانات البطاقة.']]}
};
function policyContent(page,lang='ar'){const p=pages[page];if(!p)return '';const ar=lang==='ar';return `<article class="container section prose"><span class="eyebrow">MIKYAJ · KUWAIT</span><h1>${p.title[ar?1:0]}</h1>${p.sections.map(s=>`<h2>${esc(s[ar?1:0])}</h2><p>${esc(s[ar?3:2])}</p>`).join('')}${page==='contact'?`<h2>${ar?'زورينا':'Visit the shop'}</h2><p>${ar?'محل 10، سوق المباركية، شارع سوق غربللي، مدينة الكويت':'Shop 10, Souk Al-Mubarakiyah, Gharabally Souq Street, Kuwait City'}</p><p><a href="https://maps.app.goo.gl/vh2qtDojonUxaVEq9" target="_blank" rel="noopener">${ar?'افتحي الموقع على الخريطة':'Open shop location'}</a></p>`:''}<div class="button-row"><a class="button" href="https://wa.me/96566232231" target="_blank" rel="noopener">${ar?'تواصلي عبر واتساب':'WhatsApp support'}</a><a class="button secondary" href="tel:+96566232231" dir="ltr">+965 6623 2231</a></div></article>`}
module.exports={pages,policyContent};
