const assetVersion=require('../services/asset-version');
const {faviconLinks,searchConsoleMeta}=require('./site-head');
const {schema}=require('../services/site-identity');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const origin='https://mikyajkw.com';
function shell({page='home',lang='ar',title,description,content='',canonical,initial,structured,alternates,robots='index,follow'}){
 const ar=lang==='ar',t=(en,a)=>ar?a:en;
 structured=structured||schema();
 const heading=title||t('Makeup, skincare & beauty in Kuwait','مكياج وعناية بالبشرة في الكويت');
 const desc=description||t('Shop makeup, skincare and personal care at Mikyaj Kuwait. Cash on delivery. Free Kuwait delivery on orders of 10 KWD or more.','تسوقي المكياج والعناية بالبشرة والعناية الشخصية من ميكاج الكويت. الدفع عند الاستلام وتوصيل مجاني للطلبات بقيمة 10 د.ك أو أكثر.');
 const path=canonical||origin+(page==='home'?'/'+lang+'/':`/${page}.html?lang=${lang}`);
 if(page==='home'&&!alternates)alternates={ar:origin+'/ar/',en:origin+'/en/'};
 const json=v=>JSON.stringify(v).replace(/</g,'\\u003c');
 return `<!doctype html><html lang="${lang}" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(heading)} | Mikyaj Kuwait</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="${robots}"><meta name="theme-color" content="#6c3847"><link rel="canonical" href="${esc(path)}">${faviconLinks()}${searchConsoleMeta()}<link rel="stylesheet" href="/css/storefront.css?v=${assetVersion}"><meta property="og:type" content="${page==='article'?'article':'website'}"><meta property="og:title" content="${esc(heading)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${esc(path)}"><meta property="og:image" content="${esc(initial?.product?.images?.[0]?.url||origin+'/assets/images/logo-social.png')}">${alternates?Object.entries(alternates).map(([l,u])=>`<link rel="alternate" hreflang="${l}" href="${esc(u)}">`).join(''):''}${structured?`<script type="application/ld+json">${json(structured)}</script>`:''}</head><body data-page="${page}"><a class="skip-link" href="#main">${t('Skip to content','انتقلي إلى المحتوى')}</a><div id="siteHeader"><div class="announcement">${t('Free delivery on orders of 10 KWD & above','توصيل مجاني للطلبات بقيمة 10 د.ك وأكثر')}</div><header class="site-header"><div class="container header-main"><div></div><a class="wordmark" href="/?lang=${lang}" aria-label="Mikyaj Kuwait">mikyaj<span>BEAUTY · KUWAIT</span></a><div></div></div></header></div><main id="main">${content||`<div class="container section"><h1>${esc(heading)}</h1><p>${esc(desc)}</p><div class="section" aria-live="polite">${t('Loading…','جاري التحميل…')}</div></div>`}</main><div id="siteFooter"><footer class="site-footer"><div class="container"><div class="footer-brand">mikyaj</div><p>Burhan al dahabi gen trad co · <a href="https://maps.app.goo.gl/pDiAzhB5CHR2yi7CA" rel="noopener" target="_blank">${t("Visit the shop","موقع المتجر")}</a></p><p><a class="phone-highlight" dir="ltr" href="tel:+96566232231">+965 6623 2231</a> · <a href="https://www.instagram.com/mikyajkw/" rel="me noopener" target="_blank">Instagram</a></p><div class="row wrap small"><a href="/terms.html?lang=${lang}">${t('Terms','الشروط والأحكام')}</a><a href="/privacy.html?lang=${lang}">${t('Privacy','الخصوصية')}</a><a href="/returns.html?lang=${lang}">${t('Returns','الإرجاع')}</a><a href="/delivery.html?lang=${lang}">${t('Delivery','التوصيل')}</a></div></div></footer></div><div id="mobileNav"></div><noscript><p class="container notice">${t('Enable JavaScript to add products to your bag and complete checkout. For help, call +965 6623 2231.','يرجى تفعيل جافاسكريبت لإضافة المنتجات وإتمام الطلب. للمساعدة اتصلي على 6623 2231 965+.')}</p></noscript>${initial?`<script id="initialData" type="application/json">${json(initial)}</script>`:''}<script type="module" src="/js/storefront.js?v=${assetVersion}"></script></body></html>`;
}
function welcomeHero(lang){
 const {bannerMarkup}=require('../../frontend/mikyaj-demo/js/banner-markup.mjs');
 const url=width=>'/assets/images/hero-welcome-'+width+'.webp?v='+assetVersion;
 return bannerMarkup({placement:'hero',fit:'contain',link_url:'/shop.html?makeup=1',
  title_en:'Welcome to Mikyaj Kuwait',title_ar:'أهلاً بكِ في مكياج الكويت',
  image_alt_en:'Welcome to Mikyaj Kuwait: the Mikyaj logo beside makeup and skincare arranged on a stone tabletop.',
  image_alt_ar:'أهلاً بكِ في مكياج الكويت: شعار مكياج بجانب منتجات المكياج والعناية بالبشرة على سطح حجري.',
  image_url:url(1600),image_width:1600,image_height:703
 },lang,{responsiveImages:[480,800,1200,1600].map(width=>({url:url(width),width}))});
}
function homeContent(lang='ar',settings={},banners=[]){
 const t=(en,ar)=>lang==='ar'?ar:en;
 let html=`<div class="container"><div data-banner-slot="hero">${welcomeHero(lang)}<!--/banner-slot--></div><div data-banner-slot="after_hero"><!--/banner-slot--></div><div class="benefits"><span>${t('Free delivery from 10 KWD','توصيل مجاني من 10 د.ك')}</span><span>${t('Cash on delivery','الدفع عند الاستلام')}</span><span>${t('Here to help:','للمساعدة:')} <a class="phone-highlight" href="https://wa.me/96566232231" dir="ltr">+965 6623 2231</a></span></div><section class="section"><div class="section-head"><h2>${t('Shop by category','تسوقي حسب الفئة')}</h2><button class="text-button" id="allCategories" aria-expanded="false" aria-controls="homeCategories" hidden>${t('All categories','جميع الفئات')}</button></div><div class="category-grid" id="homeCategories"></div></section><section class="section" style="padding-top:0"><div class="section-head"><div><span class="eyebrow">${t('THE BEAUTY EDIT','مختارات الجمال')}</span><h2>${t('Make room for something lovely','إضافات تستحق مكاناً في حقيبتك')}</h2></div><a class="section-link" href="/shop.html?lang=${lang}">${t('View all','عرض الكل')}</a></div><div id="homeProducts"></div></section><section class="section" id="homeBrandSection" hidden><div class="section-head"><h2>${t('Shop by brand','تسوقي حسب الماركة')}</h2><a class="section-link" href="/brands.html?lang=${lang}">${t('All brands','جميع الماركات')}</a></div><div class="brand-grid" id="homeBrands"></div></section><section class="section editorial"><a class="editorial-card" href="/shop.html?lang=${lang}&skincare=1"><div><span class="eyebrow">${t('A MOMENT FOR YOU','وقت لنفسك')}</span><h3>${t('Your skincare shelf, refreshed.','جدّدي روتين العناية.')}</h3><span class="section-link">${t('Explore skincare','اكتشفي العناية بالبشرة')} ↗</span></div><img src="/assets/images/product_serum.webp" alt="${t('Skincare serum','سيروم للعناية بالبشرة')}" loading="lazy" width="300" height="300"></a><a class="editorial-card" href="/shop.html?lang=${lang}&offers=true"><div><span class="eyebrow">${t('A LITTLE EXTRA','اختيارات أكثر')}</span><h3>${t('Good finds.<br>Lovely prices.','منتجات تحبينها.<br>بأسعار أجمل.')}</h3><span class="section-link">${t('Discover offers','اكتشفي العروض')} ↗</span></div><img src="/assets/images/product_eyeshadow.webp" alt="${t('Eyeshadow palette','لوحة ظلال عيون')}" loading="lazy" width="300" height="300"></a></section><section class="section" id="homeRecommended"></section></div>`;
 html=html.replace('<section class="section" style="padding-top:0">','<div data-banner-slot="after_categories"><!--/banner-slot--></div><section class="section" style="padding-top:0">');
 html=html.replace('<section class="section" id="homeBrandSection"','<div data-banner-slot="after_featured"><!--/banner-slot--></div><section class="section" id="homeBrandSection"');
 html=html.replace('<section class="section" id="homeRecommended"></section>','<section class="section" id="homeRecommended"></section><div data-banner-slot="before_footer"><!--/banner-slot--></div>');
 return require('../services/storefront-banners').apply(html,banners,lang);
}
module.exports={shell,homeContent,esc,origin};
