BEGIN;
ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS items JSONB NOT NULL DEFAULT '[]';
ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS reason_code TEXT NOT NULL DEFAULT 'OTHER';
ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS whatsapp_handoff_at TIMESTAMPTZ;
CREATE TABLE IF NOT EXISTS return_evidence (
 id UUID PRIMARY KEY, return_id INTEGER NOT NULL REFERENCES return_requests(id) ON DELETE CASCADE,
 image BYTEA NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS return_history (
 id BIGSERIAL PRIMARY KEY, return_id INTEGER NOT NULL REFERENCES return_requests(id) ON DELETE CASCADE,
 status TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', admin_id INTEGER REFERENCES admin_users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMIT;
