BEGIN;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS inventory_reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK(inventory_reserved_quantity>=0);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(10,3) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_details JSONB NOT NULL DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS custom_fields JSONB NOT NULL DEFAULT '{}';
COMMIT;
