export const $=(s,root=document)=>root.querySelector(s);
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const params=new URLSearchParams(location.search);
const routeLang=location.pathname.match(/^\/(ar|en)(?:\/|$)/)?.[1];
export let lang=routeLang||params.get('lang')||localStorage.getItem('mikyaj_lang')||'ar';if(!['en','ar'].includes(lang))lang='ar';
document.documentElement.lang=lang;document.documentElement.dir='ltr';localStorage.setItem('mikyaj_lang',lang);
export const t=(en,ar)=>lang==='ar'?ar:en;
export const name=p=>p?.['name_'+lang]||p?.name_ar||p?.name_en||t('Product','منتج');
export const kwd=v=>Number(v||0).toFixed(3)+' '+t('KWD','د.ك');
export const url=(file,query={})=>file==='index.html'?'/'+lang+'/':'/'+file+'?'+new URLSearchParams({lang,...query});
export const productUrl=p=>`/${lang}/products/${encodeURIComponent(p.slug)}`;
export const categoryUrl=c=>`/${lang}/categories/${encodeURIComponent(c.slug)}`;
export const articleUrl=p=>`/${lang}/journal/${encodeURIComponent(p.slug)}`;
const icons={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3z',shop:'M3 8h18l-2-5H5L3 8Zm1 0v13h16V8M9 21v-8h6v8',bag:'M5 7h14l1 14H4L5 7Zm3 0V6a4 4 0 0 1 8 0v1',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',user:'M20 21v-2a8 8 0 0 0-16 0v2M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',arrow:'M5 12h14m-6-6 6 6-6 6',check:'m5 12 4 4L19 6',close:'m6 6 12 12M6 18 18 6',truck:'M1 3h14v13H1zM15 8h4l3 4v4h-7M7 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0m14 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0',offers:'M2 3h9l11 11-9 9L2 12V3Zm5 4h.01',filter:'M3 6h18M6 12h12M9 18h6',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18'};
export const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.bag}"/></svg>`;
export function safeRead(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
export function toast(message){$('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),4000)}
const errorTranslations={'Please sign in.':'يرجى تسجيل الدخول.','Incorrect email or password.':'البريد الإلكتروني أو كلمة المرور غير صحيحة.','Enter a valid Kuwait phone number.':'أدخلي رقم هاتف كويتي صحيحاً.','Choose a Kuwait governorate.':'اختاري المحافظة في الكويت.','Complete the delivery address.':'يرجى إكمال عنوان التوصيل.','Your name is required.':'الاسم مطلوب.','Invalid email.':'البريد الإلكتروني غير صحيح.','A product is unavailable. Please update your bag.':'أحد المنتجات غير متوفر. يرجى تحديث الحقيبة.','Delivery to this area needs confirmation. Please contact the store or choose a configured area.':'يرجى تأكيد التوصيل إلى هذه المنطقة مع المتجر أو اختيار منطقة مدرجة.','Password recovery email is not configured. Please contact the store.':'خدمة استعادة كلمة المرور غير مفعلة بعد. يرجى التواصل مع المتجر.','Something went wrong. Please try again.':'حدث خطأ. يرجى المحاولة مرة أخرى.','Order not found':'لم يتم العثور على الطلب. افتحي رابط التتبع الخاص أو سجلي الدخول.','This payment method is not connected.':'وسيلة الدفع هذه غير متاحة حالياً.','This record already exists.':'هذا الطلب مسجل بالفعل.','Cash on delivery is unavailable.':'الدفع عند الاستلام غير متاح حالياً.','Your bag or details changed. Refresh checkout and try again.':'تغيرت الحقيبة أو البيانات. حدّثي صفحة الطلب وحاولي مجدداً.','A return can be requested after delivery.':'يمكن طلب الإرجاع بعد استلام الطلب.'};
const serverMessage=m=>lang==='ar'?(errorTranslations[m]||m):m;
export async function api(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch('/api'+path,{credentials:'same-origin',...options,headers:{...((options.body||!['GET','HEAD'].includes(options.method||'GET'))?{'Content-Type':'application/json'}:{}),...options.headers},signal:options.signal||controller.signal,body:options.body?JSON.stringify(options.body):undefined});const data=await response.json();if(!response.ok){const e=new Error(serverMessage(typeof data.error==='string'?data.error:data.message||t('Please try again.','يرجى المحاولة مرة أخرى.')));e.status=response.status;e.data=data;throw e}return data;}catch(e){if(e.name==='AbortError')throw new Error(t('The connection took too long. Please retry.','استغرق الاتصال وقتاً طويلاً. يرجى إعادة المحاولة.'));throw e}finally{clearTimeout(timer)}}
export function imageUrl(source,width=480){if(!source)return '/assets/images/placeholder.svg';try{const u=new URL(source,location.origin);if(u.protocol!=='https:'&&u.origin!==location.origin)return '/assets/images/placeholder.svg';if(u.hostname==='res.cloudinary.com')return source.replace('/image/upload/',`/image/upload/f_auto,q_auto,c_limit,w_${width}/`);return u.href}catch{return '/assets/images/placeholder.svg'}}
export function imageTag(p,options={}){const source=p.primary_image?.url||p.images?.[0]?.url;const alt=p.primary_image?.['alt_'+lang]||name(p);return `<img src="${esc(imageUrl(source,options.width||480))}" ${source?.includes('res.cloudinary.com')?`srcset="${esc(imageUrl(source,240))} 240w, ${esc(imageUrl(source,480))} 480w, ${esc(imageUrl(source,800))} 800w" sizes="${options.large?'(max-width: 767px) 92vw, 600px':'(max-width: 767px) 44vw, 280px'}"`:''} alt="${esc(alt)}" width="${options.width||480}" height="${options.width||480}" loading="${options.eager?'eager':'lazy'}" decoding="async" ${options.eager?'fetchpriority="high"':''}>`}
const old=safeRead('mikyaj_cart',[]);let bag=Array.isArray(old)?old.filter(i=>Number.isInteger(Number(i.productId))&&Number(i.productId)>0&&Number.isInteger(Number(i.qty))&&i.qty>0).map(i=>({...i,productId:Number(i.productId),qty:Math.min(99,Number(i.qty))})):[];
export function getBag(){return bag}
function saveBag(){localStorage.setItem('mikyaj_cart',JSON.stringify(bag));sessionStorage.removeItem('mikyaj_checkout_attempt');updateBadges();window.dispatchEvent(new Event('bagchange'))}
export function addProduct(p,qty=1){if(!p?.id||p.stock_status==='OUT_OF_STOCK'||!Number.isFinite(Number(p.selling_price))){toast(t('This product is unavailable.','هذا المنتج غير متوفر.'));return}const existing=bag.find(i=>i.productId===Number(p.id));if(existing)existing.qty=Math.min(99,existing.qty+qty);else bag.push({productId:Number(p.id),qty:Math.min(99,qty),slug:p.slug,name_ar:p.name_ar,name_en:p.name_en,name:name(p),price:Number(p.selling_price),image:p.primary_image?.url||p.images?.[0]?.url});saveBag();toast(t('Added to your bag','تمت الإضافة إلى حقيبتك'))}
export function setQuantity(id,qty){if(qty<=0)bag=bag.filter(i=>i.productId!==Number(id));else{const item=bag.find(i=>i.productId===Number(id));if(item)item.qty=Math.min(99,qty)}saveBag()}
export function clearBag(){bag=[];saveBag()}
export function updateBagProducts(products){bag=bag.map(i=>{const p=products.find(p=>p.id===i.productId);return p?{...i,name_ar:p.name_ar,name_en:p.name_en,name:name(p),slug:p.slug,price:Number(p.selling_price),image:p.primary_image?.url,unavailable:p.stock_status!=='IN_STOCK'}:{...i,unavailable:true}});localStorage.setItem('mikyaj_cart',JSON.stringify(bag));updateBadges()}
export function updateBadges(){const count=bag.reduce((n,i)=>n+i.qty,0);document.querySelectorAll('[data-bag-count]').forEach(e=>{e.textContent=count;e.hidden=!count})}
export function wishlist(){const items=safeRead('mikyaj_wishlist',[]);return Array.isArray(items)?[...new Set(items.map(Number).filter(n=>Number.isInteger(n)&&n>0))]:[]}
export function toggleSaved(id){let ids=wishlist();const has=ids.includes(Number(id));ids=has?ids.filter(x=>x!==Number(id)):[...ids,Number(id)];localStorage.setItem('mikyaj_wishlist',JSON.stringify(ids));document.querySelectorAll(`[data-save="${Number(id)}"]`).forEach(e=>{e.classList.toggle('saved',!has);e.setAttribute('aria-pressed',String(!has))});toast(has?t('Removed from saved products','تمت الإزالة من المفضلة'):t('Saved to your wishlist','تمت الإضافة إلى المفضلة'))}
export function card(p,admin=false){const saved=wishlist().includes(p.id);return `<article class="product-card ${p.stock_status==='OUT_OF_STOCK'?'is-out-of-stock':''}" data-product-id="${p.id}"><div class="product-picture"><a href="${admin?url('product.html',{admin:1,id:p.id}):productUrl(p)}">${imageTag(p)}</a>${p.offer?`<span class="pill">−${Number(p.offer.discount_percent)}%</span>`:''}${p.stock_status==='OUT_OF_STOCK'?`<span class="stock-banner">${t('OUT OF STOCK','غير متوفر في المخزون')}</span>`:''}<button class="icon-button ${saved?'saved':''}" data-save="${p.id}" aria-label="${t('Save product','حفظ المنتج')}" aria-pressed="${saved}">${icon('heart')}</button></div><div class="product-info"><div class="product-brand">${esc(p.brand?.name||p.category?.['name_'+lang]||'Mikyaj')}</div><h3 class="product-name"><a href="${admin?url('product.html',{admin:1,id:p.id}):productUrl(p)}">${esc(name(p))}</a></h3><div class="prices"><strong>${kwd(p.selling_price)}</strong>${Number(p.regular_price)>Number(p.selling_price)?`<del>${kwd(p.regular_price)}</del>`:''}</div><button class="product-add" data-add="${p.id}" ${p.stock_status==='OUT_OF_STOCK'?'disabled':''}>${p.stock_status==='OUT_OF_STOCK'?t('Out of stock','نفد المخزون'):t('Add to bag','أضيفي للحقيبة')}</button></div>${admin?`<div class="admin-controls"><button data-state="live" data-id="${p.id}">Live</button><button data-state="unlist" data-id="${p.id}">Unlist</button><button data-state="out_of_stock" data-id="${p.id}">Out of stock</button><a href="/admin/manage.html?view=product&id=${p.id}">Edit</a><button class="delete" data-state="delete" data-id="${p.id}">Delete</button><span class="small">${esc(p.status)} · ${p.priority}</span></div>`:''}</article>`}
export const skeleton=(n=4)=>`<div class="product-grid" aria-label="${t('Loading products','جاري تحميل المنتجات')}">${Array.from({length:n},()=>'<div class="skeleton"></div>').join('')}</div>`;
export function dialog(title,body){const d=document.createElement('dialog');d.className='dialog';d.innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button class="icon-button" data-close aria-label="${t('Close','إغلاق')}">${icon('close')}</button></div>${body}`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});d.showModal();return d}
export function field(label,key,value='',type='text',extra=''){return `<label class="field">${esc(label)}<input name="${esc(key)}" type="${type}" value="${esc(value)}" ${extra}></label>`}
export const errorBlock=e=>`<div class="page-error" role="alert"><p>${esc(e.message)}</p><button class="button secondary" data-retry style="margin-top:15px">${t('Try again','حاولي مرة أخرى')}</button></div>`;
export function setMeta(title,description,canonical){document.title=title+' | Mikyaj Kuwait';let desc=$('meta[name=description]');if(desc)desc.content=description;const link=$('link[rel=canonical]');if(link)link.href=canonical||location.href;}
export function statusLabel(status){const labels={PENDING_PAYMENT:['Awaiting payment','بانتظار الدفع'],CONFIRMED:['Order confirmed','تم تأكيد الطلب'],PROCESSING:['Preparing your order','جاري تجهيز طلبك'],READY_FOR_DELIVERY:['Ready to ship','جاهز للشحن'],OUT_FOR_DELIVERY:['Shipped · out for delivery','تم الشحن · في الطريق إليك'],DELIVERED:['Delivered','تم التوصيل'],CANCELLED:['Cancelled','ملغي'],RETURNED:['Returned','تم الإرجاع'],REQUESTED:['Return requested','تم طلب الإرجاع'],APPROVED:['Return approved','تم قبول الإرجاع'],REJECTED:['Return declined','تم رفض الإرجاع'],RECEIVED:['Return received','تم استلام المرتجع'],CLOSED:['Return completed','اكتمل الإرجاع']};return labels[status]?t(...labels[status]):status}
