import {$,esc,field,manage,link,panel,content,submit} from './core.js';
import {settings as legacySettings} from '../admin-legacy.js';
const sections=[['general','General'],['custom-fields','Custom fields'],['users','Users & staff'],['payments','Payments'],['checkout','Checkout'],['accounts','Customer accounts'],['shipping','Shipping & delivery'],['tax','Taxes'],['locations','Location'],['domains','Domains'],['notifications','Notifications'],['channels','Sales channels'],['social','Social profiles'],['events','Customer events'],['integrations','Integrations']];
export async function settingsPage(){const key=new URLSearchParams(location.search).get('section')||'general';const nav=`<nav class="settings-nav" aria-label="Settings sections">${sections.map(([k,title])=>`<a class="${key===k?'active':''}" href="${link(['users','custom-fields'].includes(k)?k:'settings',['users','custom-fields'].includes(k)?{}:{section:k})}">${title}</a>`).join('')}</nav>`;if(['payments','shipping','social'].includes(key)){await legacySettings();const panels=[...$('#admin-content').children];panels.forEach((p,i)=>p.hidden=i!==({shipping:0,payments:1,social:2}[key]));$('#admin-content').insertAdjacentHTML('afterbegin',nav);return}const all=await manage('/settings/sections'),s=await manage('/settings');let formKey=key,fields='',title=sections.find(x=>x[0]===key)?.[1]||'General',note='';const check=(label,name,value)=>`<label class="check-row"><input type="checkbox" name="${name}" ${value?'checked':''}>${esc(label)}</label>`;
 if(key==='tax'){fields=check('Enable additional tax','enabled',all.tax.enabled)+field('Tax label','label',all.tax.label||'Tax')+field('Rate (%)','rate',all.tax.rate||0,'number','min="0" max="100" step="0.001"')+check('Tax delivery fees','shipping_taxable',all.tax.shipping_taxable);note='Tax is disabled by default. Configure the applicable rate with your accountant. This setting adds tax after discounts; prices in the catalog remain unchanged.'}
 if(key==='domains'){content(nav+panel('Domain configuration','<p>Primary storefront: <a href="https://mikyajkw.com/">mikyajkw.com</a></p><p>Preview origin: '+esc(location.origin)+'</p><p>DNS, certificate and production deployment status have not been verified by this admin panel. Manage them with your hosting provider.</p>'));return}
 if(key==='notifications'){content(nav+panel('Notifications','<p>In-app notifications cover new orders, return requests and low tracked stock. Open the notification button in the header to review or mark them read.</p><p>Automated email and SMS delivery are not connected. Password recovery email requires server configuration.</p>'));return}
 if(key==='channels'){content(nav+panel('Sales channels','<p>Online Store · Arabic and English · KWD</p><a class="button secondary" href="'+link('online-store')+'">Manage online store</a>'));return}
 if(key==='general')fields=field('Customer-care WhatsApp (965 + 8 digits)','whatsapp',s.contact.whatsapp,'tel','pattern="965[24569][0-9]{7}" required')+field('Store name','store_name',all.general.store_name||'Mikyaj Kuwait','text','required')+field('Support email','email',all.general.email||s.contact.email,'email')+field('Phone','phone',all.general.phone||s.contact.whatsapp);
 if(key==='locations'){formKey='location';fields=field('Location name','name',all.location.name||'Mikyaj Kuwait')+field('English address','address_en',all.location.address_en||'Shop 10, Souk Al-Mubarakiyah, Gharabally Souq St, Kuwait City')+field('Arabic address','address_ar',all.location.address_ar)+field('Postal code','postal_code',all.location.postal_code||'525479')}
 if(key==='checkout'){fields=check('Allow guest checkout','guest_enabled',all.checkout.guest_enabled!==false)+check('Allow delivery notes','order_note_enabled',all.checkout.order_note_enabled!==false);note='Prices, delivery and availability are always checked on the server before an order is accepted.'}
 if(key==='accounts'){fields=check('Allow customer registration','registration_enabled',all.accounts.registration_enabled!==false);note='Customers sign in with email and password. Google sign-in is not connected.'}
 if(key==='events'){fields=check('Enable commerce analytics','enabled',all.events.enabled===true);note='Records page, product, cart and checkout events using a random session ID; signed-in events can be associated with the customer account ID. No IP addresses, names, email addresses, search queries or address details are stored. Browser Do Not Track and Global Privacy Control are respected. Keep your privacy policy current before enabling tracking.'}
 if(key==='integrations'){content(nav+panel('Service connections',`<p>MyFatoorah: ${s.payments.enabled?'enabled in '+esc(s.payments.mode)+' mode':'not enabled'}</p><p>Google sign-in: not configured</p><p>Email: server credentials required for password recovery</p><a class="button secondary" href="${link('translations')}">Translation tools</a><a class="button secondary" href="${link('settings',{section:'payments'})}">Payment settings</a>`));return}
 content(nav+panel(title,`<form id="section-settings"><div class="form-grid">${fields}</div><p class="small muted">${esc(note)}</p><p role="alert"></p><button type="submit" class="button">Save settings</button></form>`));submit($('#section-settings'),async(b,f)=>{f.querySelectorAll('[type=checkbox]').forEach(c=>b[c.name]=c.checked);await manage('/settings/'+formKey,{method:'PUT',body:b});if(key==='general')await manage('/settings/contact',{method:'PUT',body:{...s.contact,whatsapp:b.whatsapp,email:b.email}})});
}
